name: Create develop promotion pull request
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  developPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop
      - name: Reset promotion branch
        run: |
          git fetch origin main:main
          git reset --hard main
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: develop-promotion